[2023-05-04T05:31:58.504+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: train_ml_pipeline.train_model manual__2023-05-04T05:31:33.242556+00:00 [queued]>
[2023-05-04T05:31:58.516+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: train_ml_pipeline.train_model manual__2023-05-04T05:31:33.242556+00:00 [queued]>
[2023-05-04T05:31:58.516+0000] {taskinstance.py:1283} INFO - 
--------------------------------------------------------------------------------
[2023-05-04T05:31:58.516+0000] {taskinstance.py:1284} INFO - Starting attempt 1 of 2
[2023-05-04T05:31:58.516+0000] {taskinstance.py:1285} INFO - 
--------------------------------------------------------------------------------
[2023-05-04T05:31:58.531+0000] {taskinstance.py:1304} INFO - Executing <Task(PythonOperator): train_model> on 2023-05-04 05:31:33.242556+00:00
[2023-05-04T05:31:58.548+0000] {standard_task_runner.py:55} INFO - Started process 184 to run task
[2023-05-04T05:31:58.553+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'train_ml_pipeline', 'train_model', 'manual__2023-05-04T05:31:33.242556+00:00', '--job-id', '115', '--raw', '--subdir', 'DAGS_FOLDER/machine_learning_trainig_dag_Septembre.py', '--cfg-path', '/tmp/tmpiefvi3_f']
[2023-05-04T05:31:58.553+0000] {standard_task_runner.py:83} INFO - Job 115: Subtask train_model
[2023-05-04T05:31:58.617+0000] {task_command.py:389} INFO - Running <TaskInstance: train_ml_pipeline.train_model manual__2023-05-04T05:31:33.242556+00:00 [running]> on host eb31f24fc260
[2023-05-04T05:31:58.688+0000] {taskinstance.py:1511} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=train_ml_pipeline
AIRFLOW_CTX_TASK_ID=train_model
AIRFLOW_CTX_EXECUTION_DATE=2023-05-04T05:31:33.242556+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-05-04T05:31:33.242556+00:00
[2023-05-04T05:31:59.637+0000] {logging_mixin.py:137} WARNING - wandb: Tracking run with wandb version 0.15.1
[2023-05-04T05:31:59.637+0000] {logging_mixin.py:137} WARNING - wandb: Run data is saved locally in /opt/***/wandb/run-20230504_053159-zjtaqtrs
wandb: Run `wandb offline` to turn off syncing.
[2023-05-04T05:31:59.641+0000] {logging_mixin.py:137} WARNING - wandb: Syncing run 2023-05-04-05-31-58_model
[2023-05-04T05:31:59.642+0000] {logging_mixin.py:137} WARNING - wandb:  View project at https://wandb.ai/0xasept/MichelLaPolice
[2023-05-04T05:31:59.642+0000] {logging_mixin.py:137} WARNING - wandb:  View run at https://wandb.ai/0xasept/MichelLaPolice/runs/zjtaqtrs
[2023-05-04T05:31:59.646+0000] {taskinstance.py:1772} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 192, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/script.py", line 44, in train_model
    vocab = pickle.load(open("vectorize_layer_vocab.pkl", 'rb'))
FileNotFoundError: [Errno 2] No such file or directory: 'vectorize_layer_vocab.pkl'
[2023-05-04T05:31:59.657+0000] {taskinstance.py:1322} INFO - Marking task as UP_FOR_RETRY. dag_id=train_ml_pipeline, task_id=train_model, execution_date=20230504T053133, start_date=20230504T053158, end_date=20230504T053159
[2023-05-04T05:31:59.680+0000] {standard_task_runner.py:100} ERROR - Failed to execute job 115 for task train_model ([Errno 2] No such file or directory: 'vectorize_layer_vocab.pkl'; 184)
[2023-05-04T05:31:59.728+0000] {local_task_job.py:159} INFO - Task exited with return code 1
[2023-05-04T05:31:59.761+0000] {taskinstance.py:2582} INFO - 0 downstream tasks scheduled from follow-on schedule check
