[2023-05-04T05:42:43.160+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: train_ml_pipeline.train_model manual__2023-05-04T05:35:19.377444+00:00 [queued]>
[2023-05-04T05:42:43.180+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: train_ml_pipeline.train_model manual__2023-05-04T05:35:19.377444+00:00 [queued]>
[2023-05-04T05:42:43.181+0000] {taskinstance.py:1283} INFO - 
--------------------------------------------------------------------------------
[2023-05-04T05:42:43.181+0000] {taskinstance.py:1284} INFO - Starting attempt 2 of 2
[2023-05-04T05:42:43.182+0000] {taskinstance.py:1285} INFO - 
--------------------------------------------------------------------------------
[2023-05-04T05:42:43.209+0000] {taskinstance.py:1304} INFO - Executing <Task(PythonOperator): train_model> on 2023-05-04 05:35:19.377444+00:00
[2023-05-04T05:42:43.242+0000] {standard_task_runner.py:55} INFO - Started process 432 to run task
[2023-05-04T05:42:43.249+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'train_ml_pipeline', 'train_model', 'manual__2023-05-04T05:35:19.377444+00:00', '--job-id', '123', '--raw', '--subdir', 'DAGS_FOLDER/machine_learning_trainig_dag_Septembre.py', '--cfg-path', '/tmp/tmpo5f7oq2p']
[2023-05-04T05:42:43.250+0000] {standard_task_runner.py:83} INFO - Job 123: Subtask train_model
[2023-05-04T05:42:43.385+0000] {task_command.py:389} INFO - Running <TaskInstance: train_ml_pipeline.train_model manual__2023-05-04T05:35:19.377444+00:00 [running]> on host a56965e145a9
[2023-05-04T05:42:43.507+0000] {taskinstance.py:1511} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=train_ml_pipeline
AIRFLOW_CTX_TASK_ID=train_model
AIRFLOW_CTX_EXECUTION_DATE=2023-05-04T05:35:19.377444+00:00
AIRFLOW_CTX_TRY_NUMBER=2
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-05-04T05:35:19.377444+00:00
[2023-05-04T05:42:44.495+0000] {logging_mixin.py:137} WARNING - wandb: Tracking run with wandb version 0.15.1
[2023-05-04T05:42:44.495+0000] {logging_mixin.py:137} WARNING - wandb: Run data is saved locally in /opt/***/wandb/run-20230504_054243-9hyw2scv
wandb: Run `wandb offline` to turn off syncing.
[2023-05-04T05:42:44.502+0000] {logging_mixin.py:137} WARNING - wandb: Syncing run 2023-05-04-05-42-43_model
[2023-05-04T05:42:44.503+0000] {logging_mixin.py:137} WARNING - wandb:  View project at https://wandb.ai/0xasept/MichelLaPolice
[2023-05-04T05:42:44.503+0000] {logging_mixin.py:137} WARNING - wandb:  View run at https://wandb.ai/0xasept/MichelLaPolice/runs/9hyw2scv
[2023-05-04T05:42:44.860+0000] {logging_mixin.py:137} INFO - Erreur lors du téléchargement du fichier.
[2023-05-04T05:42:44.860+0000] {taskinstance.py:1772} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 192, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/script.py", line 57, in train_model
    print("vocab loaded")
FileNotFoundError: [Errno 2] No such file or directory: './vectorize_layer_vocab.pkl'
[2023-05-04T05:42:44.875+0000] {taskinstance.py:1322} INFO - Marking task as FAILED. dag_id=train_ml_pipeline, task_id=train_model, execution_date=20230504T053519, start_date=20230504T054243, end_date=20230504T054244
[2023-05-04T05:42:44.899+0000] {standard_task_runner.py:100} ERROR - Failed to execute job 123 for task train_model ([Errno 2] No such file or directory: './vectorize_layer_vocab.pkl'; 432)
[2023-05-04T05:42:44.942+0000] {local_task_job.py:159} INFO - Task exited with return code 1
[2023-05-04T05:42:44.987+0000] {taskinstance.py:2582} INFO - 0 downstream tasks scheduled from follow-on schedule check
